[tool.poetry]
name = "cartucho"
version = "0.1.0a1"
description = "A tool to cache function and method results"
readme = "README.md"
authors = ["Pablo Muñoz <pablerass@gmail.com>"]
license = "LGPL-3.0-or-later"
homepage = "https://github.com/pablerass/cartucho"
keywords = ["cache", "function", "method", "decorator"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
  "Programming Language :: Python :: 3.10",
  "Typing :: Typed",
]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.group.test.dependencies]
pytest = "*"
flake8 = "*"
coverage = "*"
mypy = "*"

[tool.poetry.group.dev.dependencies]
bumpver = "*"
ipython = "*"
ipdb = "*"
build = "*"

[tool.poetry.urls]
homepage = "https://github.com/pablerass/cartucho"

[[tool.poetry.packages]]
include = "cartucho"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"

[pytest]
addopts = "--pdbcls=IPython.terminal.debugger:TerminalPdb"

[tool.coverage.run]
source = [
  "."
]
omit = [
  "conftest.py",
  "setup.py",
  "build/*",
  "dist/*",
  "docs/*",
  "tests/*",
  ".tox/*"
]

[tool.coverage.report]
fail_under = 80

[bumpver]
current_version = "v0.1.0a1"
version_pattern = "vMAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"cartucho/__init__.py" = [
    '^__version__ = "{version}"$',
]